app/api/urls.py
from django.urls import path, include, re_path
from django.views.generic import TemplateView

from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .apps import ApiConfig
from .views import (
    PostViewSet,
    PostLikeAPIView,
    CommentLikeAPIView,
    PostActiveAPIView,
    CommentActiveAPIView,
)
from .schema import schema_view
from config.settings import COMMENTS_ENABLED, LIKES_ENABLED

app_name = ApiConfig.name

router = DefaultRouter()
router.register("posts", PostViewSet, basename="Post")

urlpatterns = [
    path("v1/", include(router.urls)),
    path("post_active/<int:post_id>/", PostActiveAPIView.as_view(), name="post_active"),
    # Авторизация по JWT токену
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    # Документация Swagger
    path(
        "swagger-ui/",
        TemplateView.as_view(
            template_name="swaggerui/swaggerui.html",
            extra_context={"schema_url": "openapi-schema"},
        ),
        name="swagger-ui",
    ),
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
]

if COMMENTS_ENABLED:
    urlpatterns += [
        path(
            "comment_active/<int:comment_id>/",
            CommentActiveAPIView.as_view(),
            name="comment_active",
        ),
    ]
if LIKES_ENABLED:
    urlpatterns = [
        path(
            "post_like/<int:post_id>/",
            PostLikeAPIView.as_view(),
            name="post_like",
        ),
    ]
if COMMENTS_ENABLED and LIKES_ENABLED:
    urlpatterns = [
        path(
            "comment_like/<int:comment_id>/",
            CommentLikeAPIView.as_view(),
            name="comment_like",
        ),
    ]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/auth/", include("rest_framework.urls")),
    path("api/", include("api.urls", namespace="api")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("", include("mainapp.urls", namespace="mainapp")),
    path("users/", include("userapp.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = "mainapp.views.error_400_view"
handler403 = "mainapp.views.error_403_view"
handler404 = "mainapp.views.error_404_view"
handler500 = "mainapp.views.error_500_view"

app/mainapp/urls.py
from django.urls import path
from django.core import management
from django.core.management.commands import loaddata


from .apps import MainappConfig
from . import views

app_name = MainappConfig.name

urlpatterns = [
    path("search-post-json/", views.search_post_json, name="search-post-json"),
    path("", views.all_posts, name="home"),
    path("<slug:alias>/", views.post_detail, name="post_detail"),
    path("post_new/", views.post_new, name="post-new"),
    path("<slug:alias>/edit/", views.post_edit, name="post-edit"),
    path("post_delete/<int:post_id>/", views.post_delete, name="post_delete"),
    path("post_active/<int:post_id>/", views.post_active, name="post_active"),
    path("comment_delete/<int:pk>/", views.comment_delete, name="comment_delete"),
    path("comment_active/<int:pk>/", views.comment_active, name="comment_active"),
    path("author_posts/<int:author_id>/", views.author_posts, name="author-posts"),
    path("reg_page/", views.reg_page, name="reg_page"),
    path("faq/", views.faq, name="faq"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),
    path("statistic/", views.statistic, name="statistic"),
    path("detailed_article/", views.DetailedArticle.as_view(), name="detailed_article"),
    path("create_demo_post/", views.create_demo_post, name="create_demo_post"),
    path("delete_demo_posts/", views.delete_demo_posts, name="delete_demo_posts"),
    path("create_category/", views.create_category, name="create_category"),
    path("clear_database/", views.clear_database, name="clear_database"),
    path("load_database/", views.load_database, name="load_database"),
    path("section/<slug:alias>/", views.posts_category, name="posts_category"),
]

# management.call_command(loaddata.Command(), 'test_data', verbosity=0)

app/userapp/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import userapp.views as userapp


app_name = "userapp"

urlpatterns = [
    path(
        "activate-user/<str:uidb64>/<str:token>", userapp.activate_user, name="activate"
    ),
    path("login/", userapp.login, name="login"),
    path("logout/", userapp.logout, name="logout"),
    path("register/", userapp.register, name="register"),
    path("account/", userapp.account, name="users-account"),
    path("profile/", userapp.profile, name="users-profile"),
    path("password/", userapp.change_password, name="change_password"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/userapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Skills(models.Model):
    # Модель скилов
    name = models.CharField(verbose_name="Название скила", max_length=45)
    description = models.TextField(verbose_name="Описание", blank=True, max_length=200)

    class Meta:
        verbose_name = "Скилы"
        verbose_name_plural = "Скилы"

    def __str__(self):
        return self.name


class User(AbstractUser):
    # Модель пользователя
    MALE = "M"
    FEMALE = "W"

    GENDER_CHOICES = (
        (MALE, "М"),
        (FEMALE, "Ж"),
    )
    username = models.CharField(
        verbose_name="Логин", blank=False, max_length=45, unique=True
    )
    password = models.CharField(verbose_name="Пароль", max_length=128)
    last_name = models.CharField(verbose_name="Фамилия", blank=True, max_length=45)
    first_name = models.CharField(verbose_name="Имя", blank=True, max_length=45)
    middle_name = models.CharField(verbose_name="Отчество", blank=True, max_length=45)
    avatar = models.ImageField(
        default="user.png",
        null=True,
        verbose_name="Аватар",
        upload_to="user_avatar",
        blank=True,
    )
    birthday = models.DateField(verbose_name="Дата рождения", blank=True, null=True, default=None)
    phone_number = models.CharField(verbose_name="Телефон", blank=True, max_length=15, default="")
    gender = models.CharField(
        verbose_name="Пол", max_length=6, blank=True, choices=GENDER_CHOICES, default=""
    )
    comments = models.TextField(verbose_name="O себе", blank=True, max_length=200)
    skills_id = models.ManyToManyField(Skills, verbose_name="Скилы", blank=True)
    delete = models.BooleanField(verbose_name="Удалена", default=False, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    email = models.EmailField(verbose_name="email", unique=True)
    is_email_verified = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def activate_user(self):
        self.is_active = True
        self.save()

    @property
    def is_moderator(self):
        return self.groups.filter(name="moderator").exists()

app/userapp/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    UserChangeForm,
    PasswordChangeForm,
)

User = get_user_model()


class MyUserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ("username", "password")


class MyUserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class ProfileForm(UserChangeForm):
    avatar = forms.FileField()
    avatar.widget.attrs.update({"class": "form-control"})

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "middle_name": forms.TextInput(attrs={"class": "form-control"}),
            "birthday": forms.DateInput(
                format="%Y-%m-%d",
                attrs={
                    "class": "form-control",
                    "placeholder": "Select a date",
                    "type": "date",
                },
            ),
            "phone_number": forms.TextInput(attrs={"class": "form-control"}),
            "gender": forms.Select(
                choices=model.GENDER_CHOICES, attrs={"class": "form-control input"}
            ),
            "comments": forms.TextInput(attrs={"class": "form-control"}),
        }
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "middle_name",
            "birthday",
            "avatar",
            "phone_number",
            "gender",
            "comments",
        )


class ChangePasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["old_password"].widget = forms.PasswordInput(
            attrs={"class": "form-control"}
        )
        self.fields["new_password1"].widget = forms.PasswordInput(
            attrs={"class": "form-control"}
        )
        self.fields["new_password2"].widget = forms.PasswordInput(
            attrs={"class": "form-control"}
        )

app/userapp/views.py
from importlib.resources import contents
from django.core.mail import EmailMessage
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from django.views import View
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.conf import settings
from .models import User
from .utils import generate_token
from userapp.forms import (
    MyUserRegisterForm,
    MyUserLoginForm,
    ProfileForm,
    ChangePasswordForm,
)
from django.contrib import auth
from django.urls import reverse
from mainapp.models import Category, Post


def send_activation_email(user, request):
    current_site = get_current_site(request)
    email_subject = "Активируйте свой профиль"

    email_body = render_to_string(
        "registration/activate.html",
        {
            "user": user,
            "domain": current_site,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": generate_token.make_token(user),
        },
    )

    email = EmailMessage(
        subject=email_subject,
        body=email_body,
        from_email=settings.EMAIL_FROM_USER,
        to=[user.email],
    )

    email.send()


def activate_user(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except Exception as e:
        user = None

    if user and generate_token.check_token(user, token):
        user.is_email_verified = True
        user.save()
        messages.add_message(
            request,
            messages.SUCCESS,
            "Электронный адрес пользователя проверен, теперь можете войти в свою"
            " учетную запись.",
        )

        return redirect("users:login")
    return render(request, "registration/activate-failed.html", {"user": user})


def login(request):
    login_form = MyUserLoginForm(data=request.POST)
    if request.method == "POST" and login_form.is_valid():
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return redirect("/")
    content = {"login_form": login_form}
    return render(request, "userapp/login.html", content)


def logout(request):
    auth.logout(request)
    return redirect("/")


def register(request):
    register_form = MyUserRegisterForm(request.POST, request.FILES)
    content = {"register_form": register_form}
    if request.method == "POST":
        if register_form.is_valid():
            user = register_form.save()
            # Mail activation
            send_activation_email(user, request)
            if not user.is_email_verified:
                messages.add_message(
                    request,
                    messages.ERROR,
                    "Ваш e-mail не верифицирован, пожалуйста проверьте входящее"
                    " сообщение для активации пользователя на портале. Если вы не"
                    ' получили сообщение, проверьте папку "Спам".',
                )
                return render(request, "userapp/register.html", content)
            return HttpResponseRedirect(reverse("users:login"))
    else:
        register_form = MyUserRegisterForm()

    return render(request, "userapp/register.html", content)


@login_required(login_url="/users/login")
def account(request):
    context = {"user": request.user}
    return render(request, "userapp/account.html", context)


@login_required(login_url="/users/login")
def profile(request):
    form = ProfileForm(instance=request.user)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()

    context = {"user": request.user, "form": form}
    return render(request, "userapp/profile.html", context)


def change_password(request):
    if request.method == "POST":
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password was successfully updated!")
            return redirect("users:users-profile")
        else:
            messages.error(request, "Please correct the error below.")
    else:
        form = ChangePasswordForm(request.user)
    return render(request, "userapp/change_password.html", {"form": form})

app/userapp/templates/userapp/account.html
{% extends 'base.html' %}
{% load static django_bootstrap5 %}

{% block content %}

<div>
	<div class="d-grid gap-2 col-6 mx-auto">
		<a class="btn btn-warning" href="{% url 'users:users-profile' %}">Профиль {{ user.username }}</a>
		<a class="btn btn-success" href="{% url 'mainapp:author-posts' user.id %}">Статьи {{ user.username }}</a>
        <a class="btn btn-outline-primary" href="{% url 'mainapp:post-new' %}">Создать новую статью</a>
	</div>
</div>

{% endblock %} 

app/userapp/templates/userapp/change_password.html
{% extends 'base.html' %}
{% load static django_bootstrap5 %}

{% block content %}



    <div class="d-flex justify-content-center">
        <form method="post">
            {% csrf_token %}
            {{ form.as_div }}
            <br>
            <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Сохранить</button>
        </form>
    </div>

{% endblock %} 

app/userapp/templates/userapp/login.html
{% extends 'base.html' %}
{% load static django_bootstrap5 %}

{% block content %}
<div class="regContainer">
    <div class="modal-content rounded-5 shadow bg-white">
        <div class="modal-header p-5 pb-4">
            <!-- <h5 class="modal-title">Modal title</h5> -->
            <h2  class="fw-bold mb-0">Вход</h2>
            <a href="{% url 'users:logout' %}">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></a>
        </div>
        <div  class="modal-body p-5 pt-0">
            <form action="{% url 'users:login' %}" method="post" class="" >
                {% csrf_token %}
                {% bootstrap_form login_form %}
                <div  class="form-floating mb-3">
                </div>
                <div  class="form-floating mb-3">
                </div>
                <div class="mb-3">
                    {% include 'mainapp/includes/messages.html' %}
                </div>
                <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Войти</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/userapp/templates/userapp/profile.html
{% extends 'base.html' %}
{% load static django_bootstrap5 %}

{% block content %}
<br>
<form action="" method="POST" enctype="multipart/form-data">


	<div class="container">
		<div class="row container">
			<div class="col-4">
				<div class="card card-body">
					<a href="/" class="btn btn-warning">&#8592; Вернуться на главную страничку</a>
					<hr>
					<h3 style="text-align: center;">Настройки профиля</h3>
					<hr>
					{% if request.user.avatar %}
					<img class="profile-pic" src="{{request.user.avatar.url}}">
					{% else %}
					<img class="profile-pic" src="{% static 'img/user.png' %}">
					{% endif %}
				</div>
			</div>
			<div class="col-5">
				<div class="card card-body">
					{% include 'mainapp/includes/messages.html' %}
					{% csrf_token %}
					{{ form.as_p }}
					<button type="submit" class="btn btn-primary mt-3">Обновить</button>
				</div>
			</div>
		</div>
	</div>
</form>


{% endblock %}

app/userapp/templates/userapp/register.html
{% extends 'base.html' %}
{% load static django_bootstrap5 %}

{% block content %}
<div  class="regContainer">
    <div class="modal-content rounded-5 shadow bg-white">
        <div class="modal-header p-5 pb-4 border-bottom-0">
            <!-- <h5 class="modal-title">Modal title</h5> -->
            <h2 align="center" class="title text-center">Регистрация</h2>
            <a href="{% url 'users:logout' %}">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></a>
        </div>
        <div class="modal-body p-5 pt-0">
            <form action="{% url 'users:register' %}" method="post" class="reg">
            {% csrf_token %}
            {% bootstrap_form register_form %}
            <div  class="form-floating mb-3">
            </div>
            <div  class="form-floating mb-3">
            </div>
            <div  class="form-floating mb-3">
            </div>
            <div  class="form-floating mb-3">
            <div class="mb-3">
                {% include 'mainapp/includes/messages.html' %}
            </div>
            </div>
                <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}