app/api/urls.py
from django.urls import path, include, re_path
from django.views.generic import TemplateView

from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .apps import ApiConfig
from .views import (
    PostViewSet,
    PostLikeAPIView,
    CommentLikeAPIView,
    PostActiveAPIView,
    CommentActiveAPIView,
)
from .schema import schema_view
from config.settings import COMMENTS_ENABLED, LIKES_ENABLED

app_name = ApiConfig.name

router = DefaultRouter()
router.register("posts", PostViewSet, basename="Post")

urlpatterns = [
    path("v1/", include(router.urls)),
    path("post_active/<int:post_id>/", PostActiveAPIView.as_view(), name="post_active"),
    # Авторизация по JWT токену
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    # Документация Swagger
    path(
        "swagger-ui/",
        TemplateView.as_view(
            template_name="swaggerui/swaggerui.html",
            extra_context={"schema_url": "openapi-schema"},
        ),
        name="swagger-ui",
    ),
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
]

if COMMENTS_ENABLED:
    urlpatterns += [
        path(
            "comment_active/<int:comment_id>/",
            CommentActiveAPIView.as_view(),
            name="comment_active",
        ),
    ]
if LIKES_ENABLED:
    urlpatterns = [
        path(
            "post_like/<int:post_id>/",
            PostLikeAPIView.as_view(),
            name="post_like",
        ),
    ]
if COMMENTS_ENABLED and LIKES_ENABLED:
    urlpatterns = [
        path(
            "comment_like/<int:comment_id>/",
            CommentLikeAPIView.as_view(),
            name="comment_like",
        ),
    ]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/auth/", include("rest_framework.urls")),
    path("api/", include("api.urls", namespace="api")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("", include("mainapp.urls", namespace="mainapp")),
    path("users/", include("userapp.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = "mainapp.views.error_400_view"
handler403 = "mainapp.views.error_403_view"
handler404 = "mainapp.views.error_404_view"
handler500 = "mainapp.views.error_500_view"

app/mainapp/urls.py
from django.urls import path
from django.core import management
from django.core.management.commands import loaddata


from .apps import MainappConfig
from . import views

app_name = MainappConfig.name

urlpatterns = [
    path("search-post-json/", views.search_post_json, name="search-post-json"),
    path("", views.all_posts, name="home"),
    path("<slug:alias>/", views.post_detail, name="post_detail"),
    path("post_new/", views.post_new, name="post-new"),
    path("<slug:alias>/edit/", views.post_edit, name="post-edit"),
    path("post_delete/<int:post_id>/", views.post_delete, name="post_delete"),
    path("post_active/<int:post_id>/", views.post_active, name="post_active"),
    path("comment_delete/<int:pk>/", views.comment_delete, name="comment_delete"),
    path("comment_active/<int:pk>/", views.comment_active, name="comment_active"),
    path("author_posts/<int:author_id>/", views.author_posts, name="author-posts"),
    path("reg_page/", views.reg_page, name="reg_page"),
    path("faq/", views.faq, name="faq"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),
    path("statistic/", views.statistic, name="statistic"),
    path("detailed_article/", views.DetailedArticle.as_view(), name="detailed_article"),
    path("create_demo_post/", views.create_demo_post, name="create_demo_post"),
    path("delete_demo_posts/", views.delete_demo_posts, name="delete_demo_posts"),
    path("create_category/", views.create_category, name="create_category"),
    path("clear_database/", views.clear_database, name="clear_database"),
    path("load_database/", views.load_database, name="load_database"),
    path("section/<slug:alias>/", views.posts_category, name="posts_category"),
]

# management.call_command(loaddata.Command(), 'test_data', verbosity=0)

app/userapp/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import userapp.views as userapp


app_name = "userapp"

urlpatterns = [
    path(
        "activate-user/<str:uidb64>/<str:token>", userapp.activate_user, name="activate"
    ),
    path("login/", userapp.login, name="login"),
    path("logout/", userapp.logout, name="logout"),
    path("register/", userapp.register, name="register"),
    path("account/", userapp.account, name="users-account"),
    path("profile/", userapp.profile, name="users-profile"),
    path("password/", userapp.change_password, name="change_password"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/mainapp/forms.py
from django.forms import ModelForm
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget

from .models import Post, Category, Comment

from config import settings


class PostForm(ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
    )
    category.widget.attrs.update({"class": "form-control"})

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["category"].label = "Раздел"
        self.fields["content"].label = "Содержимое"

    class Meta:
        model = Post
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "order": forms.NumberInput(attrs={"class": "form-control"}),
            "content": CKEditor5Widget(attrs={"class": "django_ckeditor_5"}),
        }
        fields = ("title", "category", "order", "content")
        exclude = [
            "user",
            "active",
            "description",
            "image",
            "is_deleted",
            "created_at",
            "updated_at",
            "objects",
            "alias",
        ]


if settings.COMMENTS_ENABLED:
    class CommentForm(forms.ModelForm):
        class Meta:
            model = Comment
            fields = ("text",)
            widgets = {
                "text": forms.Textarea(attrs={"class": "form-control"}),
            }
else:
    class CommentForm:
        pass

app/mainapp/views.py
from django.contrib.sites import management
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import TemplateView
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.db.models import Q
from django.core import serializers
from django.http import JsonResponse, Http404
from django.urls import reverse
from django.core import management
from django.core.management.commands import loaddata
from django.db.models import Count
from config.settings import BASE_DIR, COMMENTS_ENABLED, LIKES_ENABLED
from .forms import PostForm, CommentForm
from .models import Post, Category, Comment, PostLikes
from .utils import *
from userapp.models import User


class HomePageView(TemplateView):
    template_name = "home_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def error_404_view(request, exception):
    return render(request, "404.html")


def error_400_view(request, exception):
    return render(request, "400.html")


def error_403_view(request, exception):
    return render(request, "403.html")


def error_500_view(request):
    return render(request, "500.html", status=500)


class DetailedArticle(TemplateView):
    template_name = "detailed_article.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def reg_page(request):
    return render(request, "register.html")


def terms_of_service(request):
    return render(request, "terms_of_service.html")


def statistic(request):
    active_posts = Post.objects.filter(active=True, is_deleted=False)
    on_moderation_posts = Post.objects.filter(active=False, is_deleted=False)
    deleted_posts = Post.objects.filter(is_deleted=True)
    verified_user = User.objects.filter(is_email_verified=True, delete=False)
    not_verified_user = User.objects.filter(is_email_verified=False, delete=False)
    deleted_user = User.objects.filter(delete=True)
    post_likes = (
        PostLikes.objects.all()
        .values("post__title", "post")
        .annotate(dcount=Count("post"))
        .order_by("-dcount")[:10]
    )
    return render(
        request,
        "statistic.html",
        {
            "active_posts": active_posts,
            "on_moderation_posts": on_moderation_posts,
            "deleted_posts": deleted_posts,
            "verified_user": verified_user,
            "not_verified_user": not_verified_user,
            "deleted_user": deleted_user,
            "post_likes": post_likes,
        },
    )


def all_posts(request):
    search_query = request.GET.get("search", "")

    # Модератор и суперюзер видят все посты, а пользователи - только активные
    if request.user.is_authenticated and (
        request.user.is_superuser or request.user.is_moderator
    ):
        queryset = Post.objects.all()
    else:
        queryset = Post.objects.filter(active=True)

    if search_query:
        queryset = queryset.filter(
            Q(title__icontains=search_query)
            | Q(description__icontains=search_query)
            | Q(content__icontains=search_query)
        )

    # Сортировка статей
    order = request.GET.get("order", "")
    if order == "likes":
        posts = queryset.annotate(dcount=Count("post_likes")).order_by(
            "-dcount", "-created_at"
        )
    else:
        posts = queryset.order_by("-created_at")

    post_count = posts.count
    paginator = Paginator(posts, 3)
    page_obj = request.GET.get("page")
    try:
        posts = paginator.page(page_obj)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        "home_page.html",
        {
            "page_obj": page_obj,
            "posts": posts,
            "post_count": post_count,
        },
    )


def author_posts(request, author_id):
    posts = Post.objects.filter(user_id=author_id).order_by("-created_at")
    paginator = Paginator(posts, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        "home_page.html",
        {"page_obj": page_obj, "posts": posts},
    )


@login_required(login_url="/users/login")
def post_new(request):
    context = {}
    form = PostForm(request.POST, request.FILES)

    if request.method == "POST":
        if form.is_valid():
            result = form.save(commit=False)
            result.user = request.user
            result.save()
            return redirect("/")

    context = {"form": form}
    return render(request, "article.html", context)


@login_required(login_url="/users/login")
def post_edit(request, alias):
    post = get_object_or_404(Post, alias=alias)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            result = form.save(commit=False)
            if request.user.is_superuser:
                result.user = post.user
            else:
                result.user = request.user
            result.save()
            return redirect(reverse("mainapp:post_detail", kwargs={"alias": result.alias}))
    elif request.method == "GET":
        data = {
            "title": post.title,
            "description": post.description,
            "category": post.category,
            "content": post.content,
        }
        form = PostForm(initial=data)
    else:
        pass

    context = {"form": form}
    return render(request, "article.html", context)


@login_required(login_url="/users/login")
def post_delete(request, post_id):
    post_owner = Post.objects.values("user").get(pk=post_id)["user"]
    if (
        request.user.id == post_owner
        or request.user.is_superuser
        or request.user.is_moderator
    ):
        Post.objects.get(pk=post_id).delete()
    return redirect("/")


@login_required(login_url="/users/login")
def post_active(request, post_id):
    if request.user.is_superuser or request.user.is_moderator:
        post = get_object_or_404(Post, pk=post_id)
        post.active = not post.active
        post.save()
    return redirect(request.META["HTTP_REFERER"])


def post_detail(request, alias):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, alias=alias)
        if request.user.is_superuser or request.user.is_moderator:
            # Модератор и админ видят все статьи и комменты
            if COMMENTS_ENABLED:
                comment = Comment.objects.filter(post=post).order_by("-created_at")
        else:
            # Авторизованные пользователи видять только активые, а так же
            # свои, котоыре находятся на модерации
            if COMMENTS_ENABLED:
                comment = Comment.objects.filter(
                    Q(post=post) & (Q(active=True) | Q(user=request.user.id))
                ).order_by("-created_at")
    else:
        # Неавторизованные пользователи видят только активные статьи и комменты
        post = get_object_or_404(Post, alias=alias, active=True)
        if COMMENTS_ENABLED:
            comment = Comment.objects.filter(post=post, active=True).order_by("-created_at")

    if COMMENTS_ENABLED:
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                comm = form.save(commit=False)
                # Заложил для дальнейшей реализации Комментармй на комментарий
                if request.POST.get("parent", None):
                    form.parent_id = int(request.POST.get("parent"))
                comm.user = request.user
                comm.post = post
                comm.save()
        else:
            form = CommentForm()
    context = {
        "post": post,
        "cat_selected": post.category.alias
    }
    if COMMENTS_ENABLED:
        context.update(form=form, comment=comment,)
    return render(request, "detailed_article.html", context=context)


def posts_category(request, alias):
    search_query = request.GET.get("search", "")
    queryset = Post.objects.filter(category__alias=alias)
    # Модератор и суперюзер видят все посты, а пользователи - только активные
    if request.user.is_authenticated and (
        request.user.is_superuser or request.user.is_moderator
    ):
        posts = queryset
    else:
        posts = queryset.filter(active=True)
    if posts:
        return render(
            request,
            "home_page.html",
            {
                "posts": posts,
                "cat_selected": alias,
            },
        )
    raise Http404("Category not found")


@user_passes_test(lambda u: u.is_superuser)
def create_demo_post(request):
    user = request.user
    DemoPosts.create_demo_post(user)
    return redirect("/")


@user_passes_test(lambda u: u.is_superuser)
def delete_demo_posts(request):
    posts = Post.objects.filter(title__startswith="DEMO ")
    [post.delete() for post in posts]
    return redirect("/")


@user_passes_test(lambda u: u.is_superuser)
def create_category(request):
    user = request.user
    DemoPosts.create_category(user)
    return redirect("/")


def search_post_json(request):
    search = request.GET.get("search", "")

    if not search:
        posts = Post.objects.none().values("id", "title")
    else:
        posts = (
            Post.objects.filter(Q(title__icontains=search))
            .order_by("-created_at")
            .values("id", "title")[:10]
        )

    posts = list(posts)

    return JsonResponse(posts, safe=False)


@login_required(login_url="/users/login")
def comment_delete(request, pk):
    comment_owner = Comment.objects.values("user").get(pk=pk)["user"]
    if (
        request.user.id == comment_owner
        or request.user.is_superuser
        or request.user.is_moderator
    ):
        Comment.objects.get(pk=pk).delete()

app/mainapp/templates/404_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}404 page{% endblock %}
{% block content %}
<div class="container">
    <div class="row-md-6">
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center">
                <h1 class="display-1 fw-bold">404</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
                <p class="lead">
                    The page you’re looking for doesn’t exist.
                  </p>
                <a href="/" class="btn btn-primary">Go Home</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/mainapp/templates/comment.html
{% load static django_bootstrap5 %}

<h5 class="mb-0 bg-white">Комментариев {{ comment.count }}</h5>

{% for comm in comment %}

<div class="row-md-6 bg-white">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250">
        <div class="col p-4 d-flex flex-column position-static">

            <h4 class="mb-0">{{comm.user}}</h4>
            <div class="mb-1 text-muted">Написал: <b>{{comm.created_at}}</b>

            </div>
            <p class="card-text mb-auto"> {{comm.text}}</p>
            <div class="text-end">

                {% if comm.active %}
                    <a type="button" class="btn btn-outline-warning likeButtonComment" title="Лайкнуть"
                    data-like="{% if request.user.is_authenticated %}{% url 'api:comment_like' comm.id %}{% endif %}">
                        <div class="likeContainer">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-fire" viewBox="0 0 16 16">
                                <path
                                    d="M8 16c3.314 0 6-2 6-5.5 0-1.5-.5-4-2.5-6 .25 1.5-1.25 2-1.25 2C11 4 9 .5 6 0c.357 2 .5 4-2 6-1.25 1-2 2.729-2 4.5C2 14 4.686 16 8 16Zm0-1c-1.657 0-3-1-3-2.75 0-.75.25-2 1.25-3C6.125 10 7 10.5 7 10.5c-.375-1.25.5-3.25 2-3.5-.179 1-.25 2 1 3 .625.5 1 1.364 1 2.25C11 14 9.657 15 8 15Z">
                                </path>
                            </svg>
                            <span class="likeSpanComment{% if comm.likes_count == 0 %} likeSpanHidden{% endif %}">{{ comm.likes_count }}</span>
                        </div>
                    </a>
                {% endif %}

                {% if user.is_superuser or user.is_moderator %}
                    {% if comm.active %}
                        <a type="button" class="btn btn-success commentModerButton"
                               data-cmoder="{% url 'api:comment_active' comm.id %}" title="Отклонить">Одобрено</a>
                    {% else %}
                        <a type="button" class="btn btn-danger commentModerButton"
                           data-cmoder="{% url 'api:comment_active' comm.id %}" title="Одобрить">Отклонено</a>
                    {% endif %}
                {% elif user == comm.user and not comm.active%}
                    <span class="btn btn-secondary disabled">На модерации</span>
                {% endif %}

                {% if user == comm.user or user.is_superuser or user.is_moderator %}
                    <a class="btn btn-outline-danger articleButtons" href="{% url 'mainapp:comment_delete' comm.id %}"
                        title="Удалить комментарий">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-trash3-fill" viewBox="0 0 16 16">
                            <path
                                d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z">
                            </path>
                        </svg>
                        <span class="visually-hidden">Button</span>
                    </a>
                {% endif %}

            </div>
        </div>
    </div>

</div>
{% endfor %}

{% if user.is_authenticated %}
<p>
<form id="commentForm" action="" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" method="post">
    {%csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-light btn-outline-primary me-2 mt-2" value="Отправить">Оставить комментарий</button>
</form>

</p>
{% endif %}

app/mainapp/templates/home_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная страница{% endblock %}
{% block content %}
<div class="container main homepage">
    <div class="row-md-6  bg-white homepage">
        <div class="row-md-6  bg-white homepage">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 homepage">
                <div class="col p-4 d-flex flex-column position-static homepage">
                    {% lorem 20 p %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/mainapp/templates/posts.html
{% load static %}
<div>
    {% if posts_count_enabled or posts_sorting_enabled %}
    <div class="d-flex align-self-center">
        <div class="me-auto">
            {% if posts_count_enabled %}
            <h2>Кол-во постов: {{ post_count }}</h2>
            {% endif %}
        </div>
        <div class="btn-group bg-white" role="group">
            {% if posts_sorting_enabled %}
            <a class="btn btn-sm
                {% if not request.GET.order or request.GET.order == 'new' %}btn-secondary
                {% else %}btn-outline-secondary
                {% endif %}"
                href="/?search={{ request.GET.search }}&order=new"
                role="button">Новые</a>
            <a class="btn btn-sm
                {% if request.GET.order == 'likes' %}btn-secondary
                {% else %}btn-outline-secondary
                {% endif %}"
                href="/?search={{ request.GET.search }}&order=likes"
                role="button">Лучшие</a>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% if posts %}
    {% for post in posts %}
    <a href="#">{{ post.title }}</a>

    {% comment %} <div class="row-md-6 bg-white">
        <div class="row g-0 border rounded flex-md-row mb-4 shadow-sm h-md-250">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-success">{{ post.category }}</strong>
                <h3 class="mb-0">{{ post.title }}</h3>
                {% if post.image %}
                <img class="responsive" width="100%" height="auto" src="/media/{{ post.image }}" >
                {% else %}
                <img class="responsive" width="100%" height="auto" src="{% static 'img/post_no_image.jpg' %}" >
                {% endif %}
                <div class="mb-1 text-muted">
                    {{ post.updated_at }} |
                    {% if post.user.last_name or post.user.first_name %}
                    {{ post.user.last_name }}
                    {{ post.user.first_name }}
                    {% if post.user.first_name %}
                    {{ post.user.middle_name }}
                    {% endif %}
                    {% else %}
                    {{ post.user.username }}
                    {% endif %}
                </div>
                <p class="mb-2">{{ post.content|safe|truncatewords:60 }}</p>
                <div class="btn-group">
                    <div class="col-8">
                        <a href="{% url 'mainapp:post_detail' post.id %}" class="btn btn-primary">Продолжить
                            чтение</a>
                        {% if user == post.user or user.is_superuser or user.is_moderator %}
                        <a type="button" class="btn btn-outline-success articleButtons"
                            href="{% url 'mainapp:post-edit' post.id %}" title="Редактировать статью">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-pen-fill" viewBox="0 0 16 16">
                                <path
                                d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z">
                                </path>
                            </svg>
                        </a>
                        <a type="button" class="btn btn-outline-danger articleButtons"
                            href="{% url 'mainapp:post_delete' post.id %}" title="Удалить статью">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                <path
                                d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z">
                            </path>
                            </svg>
                        </a>
                        {% if user.is_superuser or user.is_moderator %}
                        {% if post.active %}
                        <a type="button" class="btn btn-success articleModerButton"
                            data-amoder="{% url 'api:post_active' post.id %}" title="Отклонить">Одобрено</a>
                        {% else %}
                        <a type="button" class="btn btn-danger articleModerButton"
                            data-amoder="{% url 'api:post_active' post.id %}" title="Одобрить">Отклонено</a>
                        {% endif %}
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div> {% endcomment %}
    {% endfor %}
    {% endif %}
</div>
{% if posts_pagination_enabled %}
<nav class="paginationContainer" aria-label="Page navigation">
    <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">begin</span>
            </a>
        </li>
        {% endif %}
        {% for n in posts.paginator.page_range %}
        {% if posts.number == n %}
        <li class="page-item active">
            <span class="page-link">{{ n }}</span>
        </li>
        {% elif n > posts.number|add:'-5' and n < posts.number|add:'5' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.paginator.num_pages }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">end</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}